#pragma once

// actions
#define ACT_BRICK_CLICKED "BRICK_CLICKED"
#define ACT_FUNC_SELECTED "FUNC_SELECTED"
#define ACT_COUNTER_CHANGED "COUNTER_CHANGED"
#define ACT_MAP_OBJECT_CHANGED "MAP_OBJECT_CHANGED"
#define ACT_TASK_ABORTED "TASK_ABORTED"
#define ACT_SERVER_FOUND "SERVER_FOUND"
#define ACT_SYNC_OBJECT_CHANGED "SYNC_OBJECT_CHANGED"

// attributes
#define ATTR_SEEDBED_FREQUENCY "SEEDBED_FREQUENCY"
#define ATTR_SEEDBED_LASTSPAWN "SEEDBED_LAST_SPAWN"
#define ATTR_SERVER_IP "SERVER_IP"
#define ATTR_FACTION "FACTION"
#define ATTR_ENTITYTYPE "ENTITY_TYPE"
#define ATTR_MAP "MAP"
#define ATTR_BRICK_POS "BRICK_POS"
#define ATTR_CARDINALITY "CARDINALITY"
#define ATTR_PLATFORMS "PLATFORMS"

// states
#define STATE_WORKER_IDLE "WORKER_IDLE"
#define STATE_WORKER_GOTOBRIDGE "WORKER_GOTO_BRIDGE"
#define STATE_WORKER_BUILD "WORKER_BUILD"
#define STATE_WORKER_ATTRACTOR_FOLLOW "ATTRACTOR_FOLLOW"

// goals
#define GOAL_GOTO_POSITION "GOTO_POSITION"
#define GOAL_BUILD_BRIDGE "BUILD_BRIDGE"
#define GOAL_DESTROY_BRIDGE "DESTROY_BRIDGE"

#define HYDROQ_APPID 1006
#define HYDROQ_CLIENTPORT 16895
#define HYDROQ_SERVERPORT 16896

// net messages
#define NET_MULTIPLAYER_INIT "MULTIPLAYER_INIT" // server initialization
#define NET_MULTIPLAYER_COMMAND "MULTIPLAYER_COMMAND" // user command
