#pragma once

#define ACT_BRICK_CLICKED "BRICK_CLICKED"
#define ACT_FUNC_SELECTED "FUNC_SELECTED"
#define ACT_MAP_OBJECT_CHANGED "MAP_OBJECT_CHANGED"

#define ATTR_GAME_ENTITY_TYPE "GAME_ENTITY_TYPE"
#define ATTR_ENTITY_POSITION "GAME_ENTITY_POSITION"