#pragma once

// actions
#define ACT_BRICK_CLICKED "BRICK_CLICKED"
#define ACT_FUNC_SELECTED "FUNC_SELECTED"
#define ACT_MAP_OBJECT_CHANGED "MAP_OBJECT_CHANGED"

// attributes
#define ATTR_GAME_ENTITY_TYPE "GAME_ENTITY_TYPE"
#define ATTR_SEEDBED_FREQUENCY "SEEDBED_FREQUENCY"
#define ATTR_SEEDBED_LASTSPAWN "SEEDBED_LAST_SPAWN"

// states
#define STATE_WORKER_IDLE "WORKER_IDLE"
#define STATE_WORKER_GOTOBRIDGE "WORKER_GOTO_BRIDGE"
#define STATE_WORKER_BUILD "WORKER_BUILD"

// goals
#define GOAL_GOTO_POSITION "GOTO_POSITION"
#define GOAL_BUILD_BRIDGE "BUILD_BRIDGE"

// tasks
#define TASK_BRIDGE_BUILD "BRIDGE_BUILD"